config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'articles/index'
  resources :articles
  root 'articles#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  http_basic_authenticate_with name: "dhh", password: "secret", expect: [:new, :create]
  def new
      @article = Article.new
  end

  def index
      @new_articles = Article.order(created_at: :desc).limit(5)
  end

  def create
      # 创建新的一篇文章
      @article = Article.new(article_params)

      # 保存到数据库
      @article.save
      #重定向到新建的文章
      redirect_to @article
  end

  def show
      @article = Article.find(params[:id])
  end

  private
    def article_params
        params.require(:article).permit(:title,:author,:content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_footer.html.erb
<script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>
<script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
    <% if @article.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@article.errors.count, "error") %>
            prohibited this article from being saved:
          </h2>
          <ul>
            <% @article.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <!-- 设置文章内容的输入框大小-->
    <style>
        #article_content {height: 300px; width: 500px}
    </style>

    <p>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </p>

    <p>
      <%= f.label :author%>
      <%= f.text_field :author%> <!-- text_field是input标签 -->
    </p>

    <p>
      <%= f.label :content%><br>
      <%= f.text_area :content%> <!-- text_area是textarea标签 -->
    </p>

    <p>
      <%= f.submit %>
    </p>

<% end %>

app/views/articles/_header.html.erb
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <link href="css/mystyles.css" rel="stylesheet">
</head>

<nav class="navbar navbar-default">
  <div class="row-header">
    <h1 class="qiwenh1">奇闻杂潭</h1>
  </div>

  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">奇</a>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><a href="#">志怪</a></li>
        <li><a href="#">轶事</a></li>
      </ul>

      <!-- 搜索栏 -->
      <form class="navbar-form navbar-right" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-btn-default">搜</button>
      </form>
    </div>
  </div>
</nav>

app/views/articles/edit.html.erb
<%= render 'header' %>
<h1>Edit article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<%= render 'header' %>

<!-- 广告位 -->
<div class="container">                                                                                
    <div class="row row-content">                                                                        
        <h5 align=center>---广----告----位---</h2>                                                         
    </div>                                                                                               
</div>                                                                                                 

<!-- 内容 --> 
<div class="container">
    <div class="row row-content">
        <h3 align=center>新鲜出炉</h3>
        <h4 align=center>这里是一些最新的和高度热评的文章</h4>
    </div>
</div>

<div class="container">
    <div class="row">
        <!-- 热门内容 -->                                                                                  
        <div class="col-md-6 col-sm-12">
            <% @new_articles.each do |article| %>
                <ul class="list-unstyled" style="text-align: center; font-size: 18px">
                    <li><%= link_to article.title, article_path(article) %></li>
                </ul>
            <% end %>
        </div>

        <!-- 实时更新 -->
        <div class="col-md-6 col-sm-12">
            <ul class="list-unstyled" style="text-align: center">
                <li><a href="http://baidu.com">sogou</a></li>
                <li><a href="http://baidu.com">sogou</a></li> 
                <li><a href="http://baidu.com">sogou</a></li>
                <li><a href="http://baidu.com">sogou</a></li>
            </ul>
        </div>
    </div>
</div>
<%= render 'footer' %>

app/views/articles/new.html.erb
<%= render 'header' %>

<h1>New article</h1>
<%= render 'form' %>
<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<%= render 'header' %>

<% provide(:title, @article.title) %>

<div style="background: lightblue">
    <p>
        <h1 style="text-align:center"> <%= @article.title %> </h1>
    </p>

    <p>
    <h5 style="text-align:center"> <%= @article.author %> </h5>
    </p>

    <div class="container">
        <div class="row">
            <!-- 热门内容 -->                                                                                  
            <div class="col-md-8 col-sm-12 col-md-offset-2">
                <%= @article.content %>
            </div>
        </div>
    </div>
</div>

<%= link_to 'Edit', edit_article_path(@article) %>
<%= link_to 'Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
      <!-- 设置页面的title，有助于seo，默认为‘奇闻杂潭’ -->
      <title> <%= content_for?(:title) ? yield(:title) : '奇闻杂潭' %> </title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>